---
- name: Create directories for MongoDB in Linux
  file:
    path: /data/db
    state: directory
    mode: '0777'
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "CentOS"  

- name: Create directories for MongoDB
  win_file:
    path: C:\\Users\\data\\db
    state: directory
  when: ansible_facts['os_family'] == "Windows"  
