---

- name: get the username running the deploy
  become: true
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- name: Create directories for MongoDB in Linux
  become: true
  file:
    path: /data/db
    state: directory
    mode: '0777'  
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "CentOS"  

- name: Create directories for MongoDB
  win_file:
    path: C:\\Users\\data\\db
    state: directory
  when: ansible_facts['os_family'] == "Windows"  
