---
- name: Install MongoDB for Debian
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install MongoDB for RHEL
  yum:
    name: mongodb-org
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"  

- name: Install MongoDB Installer in Windows Server
  win_command: msiexec /i mongodb.msi /qb ADDLOCAL="ServerService,Client"
  args: 
    chdir: C:\\Users
  when: ansible_facts['os_family'] == "Windows"   
